IDENTITY = [
  {
    "id": "Xv6vEmmsX",
    "source_id": "HPKRwUUm0",
    "source_type": "github",
    "email": "huhefaf_axu72@gmail.com",
  },
  {
    "id": "GRlBvILVt",
    "source_id": "0ltTIABN1",
    "source_type": "github",
    "email": "binocol-ixa48@yahoo.com",
  },
  {
    "id": "hJiXq1ajZ",
    "source_id": "eZ86TyHTL",
    "source_type": "github",
    "email": "xivema_godi10@outlook.com",
  },
  {
    "id": "8qTimLbpO",
    "source_id": "4l1VFWfIK",
    "source_type": "github",
    "email": "difaya_xohe19@aol.com",
  },
  {
    "id": "EuPtE8KxZ",
    "source_id": "nbpDtgDsh",
    "source_type": "github",
    "email": "monogoz_eze43@gmail.com",
  },
  {
    "id": "uN4xZDwi0",
    "source_id": "GmQXY1xjJ",
    "source_type": "github",
    "email": "guzivez_oho97@mail.com",
  },
  {
    "id": "oZQcQrAER",
    "source_id": "j7YbpMF9p",
    "source_type": "github",
    "email": "juhe_dikoki12@yahoo.com",
  },
  {
    "id": "6vmbqTwul",
    "source_id": "n7ThlGcPA",
    "source_type": "github",
    "email": "jakuk-ohevi27@yahoo.com",
  },
  {
    "id": "AX62oqwZr",
    "source_id": "w7ZphlOlV",
    "source_type": "github",
    "email": "muduve_pize8@hotmail.com",
  },
  {
    "id": "BGhue7AWM",
    "source_id": "zLaS1Btby",
    "source_type": "github",
    "email": "zipiruz-axi79@yahoo.com",
  },
  {
    "id": "5rfaWHDwt",
    "source_id": "x0XkxJsoD",
    "source_type": "github",
    "email": "gomalig_ewa46@gmail.com",
  },
  {
    "id": "MG4NdJwh5",
    "source_id": "sHyz1oMtH",
    "source_type": "github",
    "email": "nowit_ocoki43@aol.com",
  },
  {
    "id": "RJye5V3xs",
    "source_id": "8NhMqq9JK",
    "source_type": "github",
    "email": "xadi-bewupo80@yahoo.com",
  },
  {
    "id": "ywDk7GYB0",
    "source_id": "yAGreNNnG",
    "source_type": "github",
    "email": "remise_xite59@outlook.com",
  },
  {
    "id": "4q2oPs7z6",
    "source_id": "WrDHdrpyZ",
    "source_type": "github",
    "email": "mes-imizere25@mail.com",
  },
  {
    "id": "FJjRBKETn",
    "source_id": "zPJK6LAGL",
    "source_type": "github",
    "email": "vux-eniyavo69@mail.com",
  },
  {
    "id": "ntsfxy5Ut",
    "source_id": "nuUpxDhCh",
    "source_type": "github",
    "email": "mapux_iyigu1@aol.com",
  },
  {
    "id": "G6sbSPhUE",
    "source_id": "lZxeMOteK",
    "source_type": "github",
    "email": "rida_jagene7@hotmail.com",
  },
  {
    "id": "2crdOTWSm",
    "source_id": "ttyPncrML",
    "source_type": "github",
    "email": "sasa_memiki8@outlook.com",
  },
  {
    "id": "gFEyQAcFM",
    "source_id": "UQAu2evcR",
    "source_type": "github",
    "email": "pez_uvoneyo67@aol.com",
  },
]

USER = [
  { "id": "Xv6vEmmsX", "username": "unwritten" },
  { "id": "GRlBvILVt", "username": "bury" },
  { "id": "hJiXq1ajZ", "username": "dial" },
  { "id": "8qTimLbpO", "username": "said" },
  { "id": "EuPtE8KxZ", "username": "pot" },
  { "id": "uN4xZDwi0", "username": "original" },
  { "id": "oZQcQrAER", "username": "sowse" },
  { "id": "6vmbqTwul", "username": "evaluation" },
  { "id": "AX62oqwZr", "username": "fungi" },
  { "id": "BGhue7AWM", "username": "pitch" },
  { "id": "5rfaWHDwt", "username": "literate" },
  { "id": "MG4NdJwh5", "username": "hug" },
  { "id": "RJye5V3xs", "username": "waterfowl" },
  { "id": "ywDk7GYB0", "username": "poodle" },
  { "id": "4q2oPs7z6", "username": "unamused" },
  { "id": "FJjRBKETn", "username": "decisive" },
  { "id": "ntsfxy5Ut", "username": "teach" },
  { "id": "G6sbSPhUE", "username": "gravel" },
  { "id": "2crdOTWSm", "username": "implore" },
  { "id": "gFEyQAcFM", "username": "over" },
]

PLACE = [
  {
    "id": "ZcK0caDd9",
    "name": "In penetrali",
    "address": "85 Southfield Road, London",
  },
  {
    "id": "bOAV1nHSb",
    "name": "Haec et huius",
    "address": "The Gables, Haywards Heath Road, Balcombe",
  },
  {
    "id": "WWhguh7YI",
    "name": "Hoc inmaturo interitu",
    "address": "4 Lawrence Avenue, London",
  },
  {
    "id": "7aCBHyVCe",
    "name": "Nunc vero inanes flatus quorundam",
    "address": "27 Horn Hill View, Beaminster",
  },
  { "id": "c2vdcpcH1", "name": "Et olim licet", "address": "59 Dixon Street, Irlam" },
  { "id": "sEltDDl1H", "name": "Dum apud", "address": "7 Glen Almond, Bilton" },
  { "id": "e4dFfnQQx", "name": "Dein Syria", "address": "4 Little Green, Redmarley" },
  {
    "id": "66tLVs6ap",
    "name": "Nemo quaeso miretur",
    "address": "89 Halifield Drive, Belvedere",
  },
  {
    "id": "SGZn5pJQZ",
    "name": "Sed si ille hac",
    "address": "95 Torrington Drive, Liverpool",
  },
  {
    "id": "t0EFRACHR",
    "name": "In his tractibus",
    "address": "3 Penscoins Cottages, Y Felinheli",
  },
  {
    "id": "cDha8pEGw",
    "name": "Sed fruatur sane hoc",
    "address": "1 Abbey Close, Woking",
  },
  {
    "id": "9tdv7bp0N",
    "name": "Dum haec in oriente",
    "address": "1 Chislet Park Cottages, Island Road, Hersden",
  },
  {
    "id": "dIJ8XW0z6",
    "name": "Ut enim quisque",
    "address": "Old School House, Garth",
  },
  {
    "id": "JDKLtYWmH",
    "name": "Cumque pertinacius",
    "address": "52 Ffordd Y Gamlas, Gowerton",
  },
  {
    "id": "egF3zd8AP",
    "name": "Ideoque fertur neminem",
    "address": "2 Nelson Court, Arnside",
  },
  {
    "id": "VZ1x2UJ4A",
    "name": "Iis igitur est difficilius",
    "address": "47 Croft Road, London",
  },
  {
    "id": "RVEop8SZR",
    "name": "Sed tamen haec cum",
    "address": "55 Charnwood Avenue, Thurmaston",
  },
  {
    "id": "e3zb5kCUr",
    "name": "Quaestione",
    "address": "130 Gorwel, Llanfairfechan",
  },
  {
    "id": "2g1BTSCHZ",
    "name": "Haec igitur",
    "address": "4 Alexandra Road, Burton-On-Trent",
  },
  {
    "id": "N3aX9LmeI",
    "name": "Eodem tempore Serenianus",
    "address": "Dartwood House, Redoubt Hill, Kingswear",
  },
]

PLACELIST = [
  { "id": "ysJesUggK", "name": "In penetrali" },
  { "id": "UErlIfQ92", "name": "Haec et huius" },
  { "id": "LyCNhTwy7", "name": "Hoc inmaturo interitu" },
  { "id": "LvKCueGf6", "name": "Nunc vero inanes flatus quorundam" },
  { "id": "dpNKQjalO", "name": "Et olim licet" },
  { "id": "SJGu9SbYt", "name": "Dum apud" },
  { "id": "pOzCb0TOs", "name": "Dein Syria" },
  { "id": "2KpZUbPaJ", "name": "Nemo quaeso miretur" },
  { "id": "pQWzGJsR5", "name": "In his tractibus" },
  { "id": "YYfKzkf5n", "name": "In his tractibus" },
  { "id": "Ci91a7dDb", "name": "Sed fruatur sane hoc" },
  { "id": "ya4GiH5rA", "name": "Sed fruatur sane hoc" },
  { "id": "ciuOCiUg3", "name": "Sed fruatur sane hoc" },
  { "id": "xKNCUlQDO", "name": "Cumque pertinacius" },
  { "id": "7OQGsiILL", "name": "Ideoque fertur neminem" },
  { "id": "8G4nnKK6K", "name": "Iis igitur est difficilius" },
  { "id": "uFxtjoZZz", "name": "Sed tamen haec cum" },
  { "id": "Zg3jDl6sq", "name": "Quaestione" },
  { "id": "OLAiJxTW7", "name": "Haec igitur" },
  { "id": "z2TEDWYEj", "name": "Eodem tempore Serenianus" },
]

USER_PLACELIST = [
  {
    "placelist_id": "ysJesUggK",
    "user_id": "Xv6vEmmsX",
    "created": True,
    "followed": False,
  },
  {
    "placelist_id": "UErlIfQ92",
    "user_id": "Xv6vEmmsX",
    "created": False,
    "followed": True,
  },
  {
    "placelist_id": "LyCNhTwy7",
    "user_id": "Xv6vEmmsX",
    "created": True,
    "followed": False,
  },
  {
    "placelist_id": "LvKCueGf6",
    "user_id": "Xv6vEmmsX",
    "created": False,
    "followed": True,
  },
  {
    "placelist_id": "dpNKQjalO",
    "user_id": "GRlBvILVt",
    "created": False,
    "followed": True,
  },
  {
    "placelist_id": "SJGu9SbYt",
    "user_id": "GRlBvILVt",
    "created": False,
    "followed": True,
  },
  {
    "placelist_id": "pOzCb0TOs",
    "user_id": "GRlBvILVt",
    "created": False,
    "followed": True,
  },
  {
    "placelist_id": "2KpZUbPaJ",
    "user_id": "hJiXq1ajZ",
    "created": True,
    "followed": False,
  },
  {
    "placelist_id": "pQWzGJsR5",
    "user_id": "hJiXq1ajZ",
    "created": True,
    "followed": False,
  },
  {
    "placelist_id": "YYfKzkf5n",
    "user_id": "8qTimLbpO",
    "created": False,
    "followed": True,
  },
  {
    "placelist_id": "Ci91a7dDb",
    "user_id": "EuPtE8KxZ",
    "created": False,
    "followed": True,
  },
  {
    "placelist_id": "ya4GiH5rA",
    "user_id": "uN4xZDwi0",
    "created": False,
    "followed": True,
  },
  {
    "placelist_id": "ciuOCiUg3",
    "user_id": "oZQcQrAER",
    "created": True,
    "followed": False,
  },
  {
    "placelist_id": "xKNCUlQDO",
    "user_id": "6vmbqTwul",
    "created": False,
    "followed": True,
  },
  {
    "placelist_id": "7OQGsiILL",
    "user_id": "AX62oqwZr",
    "created": True,
    "followed": False,
  },
  {
    "placelist_id": "8G4nnKK6K",
    "user_id": "BGhue7AWM",
    "created": False,
    "followed": True,
  },
  {
    "placelist_id": "uFxtjoZZz",
    "user_id": "5rfaWHDwt",
    "created": True,
    "followed": False,
  },
  {
    "placelist_id": "Zg3jDl6sq",
    "user_id": "MG4NdJwh5",
    "created": False,
    "followed": True,
  },
  {
    "placelist_id": "OLAiJxTW7",
    "user_id": "RJye5V3xs",
    "created": True,
    "followed": False,
  },
  {
    "placelist_id": "z2TEDWYEj",
    "user_id": "ywDk7GYB0",
    "created": False,
    "followed": True,
  },
]

USER_PLACELIST = [
  { "place_id": "ZcK0caDd9", "user_id": "Xv6vEmmsX", "created": True, "visited": True },
  {
    "place_id": "bOAV1nHSb",
    "user_id": "Xv6vEmmsX",
    "created": True,
    "visited": False,
  },
  {
    "place_id": "WWhguh7YI",
    "user_id": "Xv6vEmmsX",
    "created": False,
    "visited": True,
  },
  {
    "place_id": "7aCBHyVCe",
    "user_id": "Xv6vEmmsX",
    "created": False,
    "visited": True,
  },
  { "place_id": "c2vdcpcH1", "user_id": "GRlBvILVt", "created": True, "visited": True },
  {
    "place_id": "sEltDDl1H",
    "user_id": "GRlBvILVt",
    "created": False,
    "visited": True,
  },
  {
    "place_id": "e4dFfnQQx",
    "user_id": "GRlBvILVt",
    "created": True,
    "visited": False,
  },
  {
    "place_id": "66tLVs6ap",
    "user_id": "hJiXq1ajZ",
    "created": True,
    "visited": False,
  },
  {
    "place_id": "SGZn5pJQZ",
    "user_id": "hJiXq1ajZ",
    "created": False,
    "visited": True,
  },
  { "place_id": "t0EFRACHR", "user_id": "8qTimLbpO", "created": True, "visited": True },
  {
    "place_id": "cDha8pEGw",
    "user_id": "EuPtE8KxZ",
    "created": True,
    "visited": False,
  },
  {
    "place_id": "9tdv7bp0N",
    "user_id": "uN4xZDwi0",
    "created": False,
    "visited": True,
  },
  { "place_id": "dIJ8XW0z6", "user_id": "oZQcQrAER", "created": True, "visited": True },
  {
    "place_id": "JDKLtYWmH",
    "user_id": "6vmbqTwul",
    "created": False,
    "visited": True,
  },
  {
    "place_id": "egF3zd8AP",
    "user_id": "AX62oqwZr",
    "created": False,
    "visited": True,
  },
  { "place_id": "VZ1x2UJ4A", "user_id": "BGhue7AWM", "created": True, "visited": True },
]

PLACELIST_PLACE = [
  { "id": "H0icCm8cB", "placelist_id": "ysJesUggK", "place_id": "ZcK0caDd9" },
  { "id": "aVxWPeYuj", "placelist_id": "ysJesUggK", "place_id": "bOAV1nHSb" },
  { "id": "yxOmn0t3f", "placelist_id": "ysJesUggK", "place_id": "7aCBHyVCe" },
  { "id": "QnNN8EG8T", "placelist_id": "ysJesUggK", "place_id": "c2vdcpcH1" },
  { "id": "aL2bkpKJD", "placelist_id": "UErlIfQ92", "place_id": "ZcK0caDd9" },
  { "id": "qhf67Sh67", "placelist_id": "UErlIfQ92", "place_id": "WWhguh7YI" },
  { "id": "tljlHGaoW", "placelist_id": "UErlIfQ92", "place_id": "sEltDDl1H" },
  { "id": "J82f7i72J", "placelist_id": "LyCNhTwy7", "place_id": "ZcK0caDd9" },
  { "id": "riWOrkshk", "placelist_id": "LyCNhTwy7", "place_id": "bOAV1nHSb" },
  { "id": "w6XRSqovM", "placelist_id": "LvKCueGf6", "place_id": "ZcK0caDd9" },
  { "id": "hBRBcoNsg", "placelist_id": "dpNKQjalO", "place_id": "WWhguh7YI" },
  { "id": "miezv0Hjz", "placelist_id": "SJGu9SbYt", "place_id": "7aCBHyVCe" },
  { "id": "yjl8XeumN", "placelist_id": "Ci91a7dDb", "place_id": "c2vdcpcH1" },
  { "id": "M46t3PcXC", "placelist_id": "ya4GiH5rA", "place_id": "e4dFfnQQx" },
  { "id": "2rc2rifeN", "placelist_id": "ciuOCiUg3", "place_id": "bOAV1nHSb" },
  { "id": "LXYk6fh8t", "placelist_id": "xKNCUlQDO", "place_id": "66tLVs6ap" },
  { "id": "3uiUViO9N", "placelist_id": "7OQGsiILL", "place_id": "SGZn5pJQZ" },
  { "id": "2RMvuaOcU", "placelist_id": "8G4nnKK6K", "place_id": "t0EFRACHR" },
  { "id": "EwO3wd4GK", "placelist_id": "uFxtjoZZz", "place_id": "cDha8pEGw" },
  { "id": "pnhABS7nU", "placelist_id": "Zg3jDl6sq", "place_id": "9tdv7bp0N" },
  { "id": "3yg632rBu", "placelist_id": "OLAiJxTW7", "place_id": "e3zb5kCUr" },
  { "id": "zdT7DdpIn", "placelist_id": "z2TEDWYEj", "place_id": "N3aX9LmeI" },
]
